[tool.poetry]
name = "keylocker"
version = "0.1.1"
description = "Library with the CLI to save the encrypted secrets in the configuration file, but a transparent read and write the new settings in the app."
authors = ["vpuhoff <vpuhoff@live.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
pickleDB = "^0.9.2"
cryptography = "^2.7"
fire = "^0.1.3"

[tool.poetry.dev-dependencies]
python = "^3.6"
pickleDB = "^0.9.2"
cryptography = "^2.7"
fire = "^0.1.3"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = 'keylocker'